// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Luminous.TimeSavers
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "6359da17-6477-4e9c-8e73-7d05ea8a33a1";
        public const string InsertGuidToolWindowString = "776cdc3d-f8f4-4819-8141-cf5938c4cd7d";
        public const string GeneralDialogPageString = "dcbbd0f7-6463-48f4-9c86-1ce95ef7c1a2";
        public const string BuildDialogPageString = "e967a459-0b9e-4222-ba52-a66496edaee3";
        public const string DeveloperDialogPageString = "7a9f803b-96de-4d30-b1cd-590443192092";
        public const string VisualStudioDialogPageString = "13c28243-07fb-4034-a035-3a44ff0330aa";
        public const string SeparatorsDialogPageString = "736339a2-2ba5-4e37-9e55-1e72f5ae4721";
        public const string OptionsDialogPageString = "6bf7c9fa-8e42-4673-83cb-288efe5ae3b5";
        public const string PackageCommandSetString = "4eac4e23-4909-4dac-9d6e-819bdc861480";
        public static Guid Package = new Guid(PackageString);
        public static Guid InsertGuidToolWindow = new Guid(InsertGuidToolWindowString);
        public static Guid GeneralDialogPage = new Guid(GeneralDialogPageString);
        public static Guid BuildDialogPage = new Guid(BuildDialogPageString);
        public static Guid DeveloperDialogPage = new Guid(DeveloperDialogPageString);
        public static Guid VisualStudioDialogPage = new Guid(VisualStudioDialogPageString);
        public static Guid SeparatorsDialogPage = new Guid(SeparatorsDialogPageString);
        public static Guid OptionsDialogPage = new Guid(OptionsDialogPageString);
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageToolbar = 0xA001;
        public const int PackageMenu = 0xA002;
        public const int CodeEditorGroup = 0xB000;
        public const int SolutionNodeGroup = 0xC000;
        public const int ProjectNodeGroup = 0xD000;
        public const int SolutionGroup = 0x0C00;
        public const int EditSolutionCommand = 0x0C05;
        public const int CloseSolutionCommand = 0xCB06;
        public const int ProjectGroup = 0x0D00;
        public const int EditProjectCommand = 0x0D05;
        public const int InsertGroup = 0x0A00;
        public const int InsertGuidCommand = 0x0A05;
        public const int GeneralGroup = 0x0210;
        public const int BrowserWindowCommand = 0x0215;
        public const int BuildGroup = 0x0310;
        public const int RebuildProjectCommand = 0x0315;
        public const int RebuildSolutionCommand = 0x0316;
        public const int CancelBuildCommand = 0x0317;
        public const int DeveloperGroup = 0x0700;
        public const int DeveloperDropdown = 0x0701;
        public const int DeveloperCommands = 0x0702;
        public const int ActivityLogCommand = 0x0705;
        public const int DiagnosticLogCommand = 0x0706;
        public const int PathVariablesCommand = 0x0707;
        public const int VisualStudioGroup = 0x0840;
        public const int ExtensionsAndUpdatesCommand = 0x0845;
        public const int RestartGroup = 0x0900;
        public const int RestartDropDown = 0x0901;
        public const int RestartCommands = 0x0902;
        public const int RestartNormalCommand = 0x0905;
        public const int RestartElevatedCommand = 0x0906;
        public const int OptionsGroup = 0x0950;
        public const int OptionsDropDown = 0x0951;
        public const int OptionsCommands = 0x0952;
        public const int KeyboardOptionsCommand = 0x0955;
        public const int TimeSaversOptionsCommand = 0x0959;
    }
}
