// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Luminous.TimeSavers
{
    static class Vsix
    {
        public const string Id = "049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd";
        public const string Name = "Luminous Time Savers";
        public const string Description = @"TimeSavers => { developerProductivity++; }";
        public const string Language = "en-US";
        public const string Version = "2.2.1";
        public const string Author = "Luminous Software Solutions";
        public const string Tags = "time savers,visual studio,productivity,luminous,timesavers,yannduran,yd";
    }
}
