// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Luminous.TimeSavers
{
    internal sealed partial class Vsix
    {
        public const string Id = "049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd";
        public const string Name = "Time Savers";
        public const string Description = @"TimeSavers => { developerProductivity++; }";
        public const string Language = "en-US";
        public const string Version = "2.3.0.3";
        public const string Author = "Luminous Software Solutions";
        public const string Tags = "luminous,time savers,time-savers,timesavers,visual studio,productivity,guid,guid generator,guid-generator,yannduran,yd";
    }
}
